name: CI/CD pipeline

on:
  push:
    branches:
      - master

jobs:
  laravel-mongodb-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update package lists
        run: sudo apt update

      # Start MongoDB instance using action (replace version if needed)
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '4.4'  # Replace with desired version

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Update .env for MongoDB (adjust DB_HOST if using local instance)
      - name: Update .env for MongoDB
        run: |
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=mongodb/g' .env
          # Adjust DB_HOST if using the local MongoDB instance
          # sed -i 's/DB_HOST=127.0.0.1/DB_HOST=localhost/g' .env  # Uncomment if using local instance
          sed -i 's/DB_PORT=3306/DB_PORT=27017/g' .env
          sed -i 's/DB_DATABASE=laravel/DB_DATABASE=test/g' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=aicha16ettabite/g' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=2pHlyzmjkLsciADV/g' .env
          # Set DB_URI if your Laravel version supports it
          echo "DB_URI=mongodb+srv://aicha16ettabite:2pHlyzmjkLsciADV@cluster0.m5zmwul.mongodb.net/" >> .env

      - name: Install Dependencies (Laravel)
        run: composer install --prefer-dist

      - name: Generate key (Laravel)
        run: php artisan key:generate

      - name: Directory Permissions (Laravel)
        run: chmod -R 755 storage bootstrap/cache  # Fix permission issue

      - name: Execute Laravel tests via PHPUnit
        run: php artisan test --testsuite=Unit

  react-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Navigate to frontend directory
        run: cd frontend

      - name: Check nvm installation (Optional)  # Optional step
        run: which nvm

      - name: Load nvm configuration  # Added this line
        run: source ~/.nvm/nvm.sh

      - name: Setup Node.js (use pre-installed version)
        run: nvm use node

      - name: Install Dependencies (React)
        run: npm install

      - name: Build React App
        run: npm run build
        working-directory: frontend
