name: CI/CD pipeline

on:
  push:
    branches:
      - master

jobs:
  laravel-mongodb-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update package lists
        run: sudo apt update

      - name: Install MongoDB dependencies
        run: sudo apt install -y gnupg curl

      - name: Add MongoDB repository key
        run: curl -fsSL https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -

      - name: Add MongoDB repository
        run: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list

      - name: Install MongoDB
        run: sudo apt install -y mongodb-org

      - name: Start MongoDB
        run: sudo systemctl start mongod

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Update .env for MongoDB
        run: |
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=mongodb/g' .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=cluster0.m5zmwul.mongodb.net/g' .env
          sed -i 's/DB_PORT=3306/DB_PORT=27017/g' .env
          sed -i 's/DB_DATABASE=laravel/DB_DATABASE=test/g' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=aicha16ettabite/g' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=2pHlyzmjkLsciADV/g' .env
          # Set DB_URI if your Laravel version supports it
          echo "DB_URI=mongodb+srv://aicha16ettabite:2pHlyzmjkLsciADV@cluster0.m5zmwul.mongodb.net/" >> .env

      - name: Install Dependencies (Laravel)
        run: composer install --prefer-dist

      - name: Generate key (Laravel)
        run: php artisan key:generate

      - name: Directory Permissions (Laravel)
        run: chmod -R 755 storage bootstrap/cache  # Fix permission issue

      - name: Execute Laravel tests via PHPUnit
        run: php artisan test --testsuite=Unit

  react-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Navigate to frontend directory
        run: cd frontend

      - name: Check nvm installation (Optional)  # Optional step
        run: which nvm

      - name: Load nvm configuration  # Added this line
        run: source ~/.nvm/nvm.sh

      - name: Setup Node.js (use pre-installed version)
        run: nvm use node

      - name: Install Dependencies (React)
        run: npm install

      - name: Build React App
        run: npm run build
        working-directory: frontend

