name: CI/CD pipeline

on:
  push:
    branches:
      - master

jobs:
  laravel-mongodb-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update package lists
        run: sudo apt update

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '4.4'

      - name: Set up Laravel environment
        run: |
          cd backend  
          php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Update .env for MongoDB
        run: |
          cd backend
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=mongodb/g' .env
          sed -i 's/DB_PORT=3306/DB_PORT=27017/g' .env
          sed -i 's/DB_DATABASE=laravel/DB_DATABASE=test/g' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=aicha16ettabite/g' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=2pHlyzmjkLsciADV/g' .env
          echo "DB_URI=mongodb+srv://aicha16ettabite:2pHlyzmjkLsciADV@cluster0.m5zmwul.mongodb.net/" >> .env

      - name: Install Dependencies (Laravel)
        run: |
          cd backend
          composer install --ignore-platform-req=ext-mongodb

      - name: Generate key (Laravel)
        run: |
          cd backend
          php artisan key:generate

      - name: Directory Permissions (Laravel)
        run: |
          cd backend
          chmod -R 755 storage bootstrap/cache

      - name: Execute Laravel tests via PHPUnit
        run: |
          cd backend
          php artisan test --testsuite=Unit

  react-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Navigate to frontend directory
        run: cd frontend

      - name: Check nvm installation (Optional)
        run: which nvm

      - name: Load nvm configuration
        run: source ~/.nvm/nvm.sh

      - name: Setup Node.js (use pre-installed version)
        run: nvm use node

      - name: Install Dependencies (React)
        run: npm install

      - name: Build React App
        run: npm run build
        working-directory: frontend
